### ISSUE TITLE
Error in example charts on respository's README.md

### ISSUE THREAD

**Issue by bielsesa** [denoland/fresh_charts#10]
It might be a bit of a silly issue, but using the Chart examples from the repository's main README gave me a small error.

The error was due to the `options` parameter for the charts code. The current code is `scales: { yAxes: [{ ticks: { beginAtZero: true } }] }` when I guess it should be (as far as I tried) `scales: { yAxes: { beginAtZero: true } }`.

The error made VSCode give me the following error message:

```
Type '{ ticks: { beginAtZero: true; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "linear"; } & CartesianScaleOptions & { beginAtZero: boolean; suggestedMin?: number | undefined; suggestedMax?: number | undefined; grace?: string | number | undefined; ticks: { ...; }; }> | ... 5 more ... | undefined'.
  Type '{ ticks: { beginAtZero: true; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "radialLinear"; } & CoreScaleOptions & { animate: boolean; startAngle: number; angleLines: { display: boolean; color: Scriptable<Color, ScriptableScaleContext>; lineWidth: Scriptable<...>; borderDash: Scriptable<...>; borderDashOffset: Scriptable<...>; }; ... 7 more ...; ticks: RadialTickO...'.
    Types of property 'reverse' are incompatible.
      Type '() => { ticks: { beginAtZero: true; }; }[]' is not assignable to type 'boolean | undefined'.deno-ts(2322)
```

And the charts were created, but the `yAxis` did not start at 0.

I checked and in the examples folder this does not happen, so I don't really know if this should be checked or not. 
So it's just the examples on the README and it might not be much of a problem, but just wanted to notify this!

**Comment by timharek** [comment]
I figured out the fix for this:

```ts
scales: { y: { beginAtZero: true } }
```

Should be a quick fix to update the README 😊

**Comment by hashrock** [comment]
I agree with timharek. `scales: { yAxis: { ... } }` will create second y-axis scale because there's default scale named 'y'. This is why `beginAtZero` didn't effect.

Specification for Axis:

https://www.chartjs.org/docs/latest/axes/

I also agree that we should fix the example.
