### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by lambtron** [denoland/fresh_charts#11]
![image](https://github.com/denoland/fresh_charts/assets/1080190/45e83c19-1705-4cd8-83d0-b4d9ca05c11c)

**Comment by iuioiua** [comment]
+1 for this! Perhaps this could be fixed simply by adding a `class` property to the `<Chart />` passed directly to the SVG.

**Comment by iuioiua** [comment]
@kt3k, is it possible to add support for the `responsive` property?

**Comment by iuioiua** [comment]
I'd say this has been fixed by #15. Proof:
![hunt deno land_dashboard_stats(iPhone SE)](https://github.com/denoland/fresh_charts/assets/29347852/4f800c51-5cfd-440f-a41d-7f8973e4b8eb)

**Comment by kt3k** [comment]
Ok. Let's close
