### ISSUE TITLE
Support client-side rendering

### ISSUE THREAD

**Issue by ayame113** [denoland/fresh_charts#12]
When I ran this on the browser side (in islands), an error `Cannot find name 'Deno'` occurred and I could not draw.
Is it possible to make this library support client side rendering?

[preact-chartjs-2](https://github.com/bonitasoft/preact-chartjs-2), a library for using Chart.js with Preact, is archived, so it would be nice to be able to do client-side rendering with this library as well.

**Comment by lino-levan** [comment]
I believe this was done in #15

**Comment by kt3k** [comment]
right
